-- src/core/generator.lua
-- Scaffold generator: loads a template, substitutes parameters, validates
-- the result, and returns an annotated behavior table.
--
-- Usage:
--   local gen    = require("src.core.generator")
--   local result = gen.generate("hauler_loop", { pickup_register = "A", ... })
--   -- result.behavior  – filled-in behavior table
--   -- result.warnings  – list of {level, message} from the validator
--   -- result.source    – human-readable annotated source (with TODO markers)

local loader    = require("src.core.template_loader")
local validator = require("src.validators.behavior_validator")

-- Fallback for in-game paths
if not loader then loader = require("BehaviorEasyWay.src.core.template_loader") end
if not validator then validator = require("BehaviorEasyWay.src.validators.behavior_validator") end

local Generator = {}

-- ---------------------------------------------------------------------------
-- Internal helpers
-- ---------------------------------------------------------------------------

local PLACEHOLDER_PATTERN = "{{([%w_]+)}}"

--- Deep-copy a value (tables only; handles nested tables).
local function deep_copy(orig)
    local t = type(orig)
    if t ~= "table" then return orig end
    local copy = {}
    for k, v in pairs(orig) do
        copy[deep_copy(k)] = deep_copy(v)
    end
    return setmetatable(copy, getmetatable(orig))
end

--- Substitute {{PARAM}} tokens in a string value.
---@param s      string   The string to process
---@param params table    Key→value substitution map
---@return string result
---@return boolean had_placeholder  true if the original had at least one token
---@return boolean all_resolved     true if all tokens were replaced
local function substitute_string(s, params)
    local had = s:find(PLACEHOLDER_PATTERN) ~= nil
    local unresolved = false
    local result = s:gsub(PLACEHOLDER_PATTERN, function(key)
        local val = params[key]
        if val ~= nil then
            return tostring(val)
        end
        unresolved = true
        return "{{" .. key .. "}}"   -- leave token intact so validator catches it
    end)
    return result, had, not unresolved
end

--- Recursively walk a table and substitute placeholders in string values.
---@param tbl    table
---@param params table
---@return table   processed_table
---@return string[] unresolved_keys  list of placeholder names that had no value
local function substitute_table(tbl, params)
    local unresolved = {}
    local function walk(node)
        if type(node) ~= "table" then return node end
        local out = {}
        for k, v in pairs(node) do
            if type(v) == "string" then
                local replaced, had, ok = substitute_string(v, params)
                out[k] = replaced
                if had and not ok then
                    -- collect the unresolved token names from the original value
                    for token in v:gmatch(PLACEHOLDER_PATTERN) do
                        if params[token] == nil then
                            unresolved[#unresolved + 1] = token
                        end
                    end
                end
            elseif type(v) == "table" then
                out[k] = walk(v)
            else
                out[k] = v
            end
        end
        return out
    end
    return walk(tbl), unresolved
end

--- Check that all required parameters declared in the template are present.
---@param template table
---@param params   table
---@return string[] missing list of required param names that are absent
local function check_required_params(template, params)
    local missing = {}
    if type(template.params) ~= "table" then return missing end
    for _, param_def in ipairs(template.params) do
        if param_def.required and params[param_def.name] == nil then
            missing[#missing + 1] = param_def.name
        end
    end
    return missing
end

--- Build the human-readable annotated source string.
---@param template  table
---@param behavior  table  (already substituted)
---@param params    table
---@return string
local function build_source(template, behavior, params)
    local lines = {}
    lines[#lines + 1] = "-- Generated by BehaviorEasyWay from template: " .. (template.id or "?")
    lines[#lines + 1] = "-- Template version: " .. (template.version or "unknown")
    lines[#lines + 1] = "--"
    lines[#lines + 1] = "-- Parameters used:"
    if type(template.params) == "table" then
        for _, pd in ipairs(template.params) do
            local val = params[pd.name]
            if val ~= nil then
                lines[#lines + 1] = "--   " .. pd.name .. " = " .. tostring(val)
            else
                lines[#lines + 1] = "--   " .. pd.name .. " = (not set)"  -- TODO: provide a value
            end
        end
    end
    lines[#lines + 1] = ""
    lines[#lines + 1] = "-- TODO: Review generated nodes below and fill in any remaining {{PLACEHOLDERS}}"
    lines[#lines + 1] = ""

    -- Simple serialization of the behavior table for human review
    local function ser(v, indent)
        indent = indent or 0
        local pad = string.rep("  ", indent)
        if type(v) == "table" then
            local parts = {}
            for k2, v2 in pairs(v) do
                local key = type(k2) == "string" and (k2 .. " = ") or ""
                parts[#parts + 1] = pad .. "  " .. key .. ser(v2, indent + 1)
            end
            return "{\n" .. table.concat(parts, ",\n") .. "\n" .. pad .. "}"
        elseif type(v) == "string" then
            return string.format("%q", v)
        else
            return tostring(v)
        end
    end

    lines[#lines + 1] = "return " .. ser(behavior, 0)
    return table.concat(lines, "\n")
end

-- ---------------------------------------------------------------------------
-- Public API
-- ---------------------------------------------------------------------------

--- Return a list of all available template names.
---@return string[]
function Generator.list_templates()
    return loader.list()
end

--- Generate a behavior scaffold from a named template and parameters.
---
---@param template_name string   Template identifier (e.g. "hauler_loop")
---@param params        table    Key→value map of parameter values
---@return table result
---   result.behavior  table     – substituted behavior definition
---   result.warnings  table[]   – [{level, message}] from validator
---   result.source    string    – annotated Lua source with TODO markers
---   result.ok        boolean   – false if there were errors
function Generator.generate(template_name, params)
    params = params or {}

    -- 1. Load template
    local tmpl, load_err = loader.load(template_name)
    if not tmpl then
        return {
            ok       = false,
            behavior = nil,
            warnings = { { level = "error", message = load_err or "Unknown template: " .. template_name } },
            source   = "-- ERROR: " .. (load_err or "Unknown template"),
        }
    end

    -- 2. Check required params
    local missing = check_required_params(tmpl, params)
    local warnings = {}
    for _, m in ipairs(missing) do
        warnings[#warnings + 1] = {
            level   = "error",
            message = "Missing required parameter: " .. m,
        }
    end

    -- 3. Merge defaults
    local merged_params = {}
    if type(tmpl.params) == "table" then
        for _, pd in ipairs(tmpl.params) do
            if pd.default ~= nil and params[pd.name] == nil then
                merged_params[pd.name] = pd.default
            end
        end
    end
    for k, v in pairs(params) do
        merged_params[k] = v
    end

    -- 4. Substitute placeholders in the behavior graph
    local behavior_copy = deep_copy(tmpl.behavior or {})
    local substituted, unresolved = substitute_table(behavior_copy, merged_params)

    for _, token in ipairs(unresolved) do
        warnings[#warnings + 1] = {
            level   = "warning",
            message = "Unresolved placeholder: {{" .. token .. "}}",
        }
    end

    -- 5. Run structural validator
    local val_messages = validator.validate(substituted)
    for _, msg in ipairs(val_messages) do
        warnings[#warnings + 1] = msg
    end

    -- 6. Build annotated source
    local source = build_source(tmpl, substituted, merged_params)

    local has_errors = false
    for _, w in ipairs(warnings) do
        if w.level == "error" then has_errors = true; break end
    end

    return {
        ok       = not has_errors,
        behavior = substituted,
        warnings = warnings,
        source   = source,
    }
end

return Generator
